version: '3.8'

services:
  bootstrap-redis:
    image: 'redis:7'
    networks:
      - discourse
  bootstrap-postgres:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_DB: bootstrap
      POSTGRES_USER: bootstrap
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - discourse

networks:
  discourse:
    name: discourse
    attachable: true