name: CENV Deployment CI

on:
  push:
    paths:
      - 'templates/container-env/**'
      - '.github/workflows/cenv-deployment.yml'
    branches: [ "main" ]

  workflow_run:
    workflows: ["VNet Deployment CI"]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get last vnet data
        id: vnet-data
        run: |
          output=$(az deployment group show -n ${{ vars.VNET_DEPLOYMENT_NAME }} -g ${{ vars.VNET_RESOURCE_GROUP }})
          containersSubnetId=$(echo $output | jq -r '.properties.outputs.containerAppsSubnetId.value')
          echo "CONTAINERS_SUBNET_ID=$containersSubnetId" >> "$GITHUB_OUTPUT"

      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Deploy Container Environment Resources
        uses: Azure/cli@v2.0.0
        env:
          CONTAINERS_SUBNET_ID: ${{ steps.vnet-data.outputs.CONTAINERS_SUBNET_ID }}
        with:
          inlineScript: |
            az deployment group create \
              --name ${{ vars.CENV_DEPLOYMENT_NAME }} \
              --resource-group ${{ vars.CENV_RESOURCE_GROUP }} \
              --template-file ./templates/container-env/main.bicep \
              --parameters \
                containerEnvName='${{ vars.CENV_NAME }}' \
                containerAppSubnetId=$CONTAINERS_SUBNET_ID
