name: SMTP Deployment CI

on:
  push:
    paths:
      - 'templates/smtp/**'
      - '.github/workflows/smtp-deployment.yml'
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout current branch
        uses: actions/checkout@v3


      - name: Deploy SMTP Resources
        uses: Azure/cli@v2.0.0
        with:
          inlineScript: |
            az deployment group create \
              --name ${{ vars.ECS_DEPLOYMENT_NAME }} \
              --resource-group ${{ vars.ECS_RESOURCE_GROUP }} \
              --template-file ./templates/smtp/main.bicep \
              --parameters \
                ecsName='${{ vars.ECS_NAME }}' \
                domainName='${{ secrets.DOMAIN_NAME }}' \
                appRegAppId='${{ secrets.ECS_APPREG_ID }}' \
                appRegClientSecret='${{ secrets.ECS_APPREG_SECRET }}' \
                appRegTenantId='${{ secrets.AZURE_TENANT_ID }}' \
                appRegPrinId='${{ secrets.ECS_APPREG_PRIN_ID }}'
